### ISSUE TITLE
Links to source data should not take the user to CKAN

### ISSUE THREAD

**Issue by acorbi** [OpenDevelopmentMekong/wp-odm_dash#10]
the links to the data source should take the user to the dataset detail page in WP and not to CKAN. Alternativelly, you can just expose the direct download link
that means that you would need to replace https://data.opendevelopmentmekong.net/dataset/7bc0cabc-3c01-44fe-ba30-943a360c56fb/resource/d646bd1e-f377-4152-a4a7-8785e2b39fc5 with https://myanmar.pp.opendevelopmentmekong.net/dataset/?id=7bc0cabc-3c01-44fe-ba30-943a360c56fb or with https://data.opendevelopmentmekong.net/dataset/7bc0cabc-3c01-44fe-ba30-943a360c56fb/resource/d646bd1e-f377-4152-a4a7-8785e2b39fc5/download/HouseholdspopulationBasedDatasetSRUnion.csv

**Comment by DragonVirus** [comment]
Fixed via 49f31bc5cbff19a46a472939992c4eff8d181083
