### ISSUE TITLE
ODMM: The table displays ‘NaN’ for the first two are these ‘not applicable’ meaning that there aren’t any or is this an error?

### ISSUE THREAD

**Issue by thetaung2** [OpenDevelopmentMekong/wp-odm_dash#15]
![capture 1](https://cloud.githubusercontent.com/assets/20394487/18509320/f390621e-7a9d-11e6-9e0f-8ab9a2683adb.PNG)

The table displays ‘NaN’ for the first two are these ‘not applicable’ meaning that there aren’t any or is this an error?

**Comment by DragonVirus** [comment]
Fixed via f808176b7a0137edfe85fb90057f08851d75781c
