### ISSUE TITLE
ODMM: The total population should include both enumerated and non-enumerated figures

### ISSUE THREAD

**Issue by thetaung2** [OpenDevelopmentMekong/wp-odm_dash#17]
We need to show total population (Both enumerated and non-enumerated) for Union, Kachin, Kayin and Rakhine. That’s not in census dataset, can we add that manually? Can we also show enumerated and non-enumerated seperately?

**Comment by acorbi** [comment]
Please add description of the methodology on the corresponding dataset: https://myanmar.opendevelopmentmekong.net/dataset?id=7bc0cabc-3c01-44fe-ba30-943a360c56fb
https://data.opendevelopmentmekong.net/dataset/7bc0cabc-3c01-44fe-ba30-943a360c56fb/

**Comment by DragonVirus** [comment]
Fixed via d99d475a1ca0edced4cc0f89461aee7d4e7e8b8a

**Comment by acorbi** [comment]
Closing
