### ISSUE TITLE
ODMM Dashboard : Optimize responsive view 

### ISSUE THREAD

**Issue by DragonVirus** [OpenDevelopmentMekong/wp-odm_dash#57]
Optimize navigation bar, general info box and some visualization views for mobile devices. 

![image](https://cloud.githubusercontent.com/assets/1311765/20698153/653ec642-b62d-11e6-82b3-fcfeceba4ba5.png)

**I will take care of it. Just opening issue for record**

**Comment by acorbi** [comment]
you can assign yourself the issue for indicating that you will take care of it
--
Gesendet von der myMail-App für Android Dienstag, 29 November 2016, 06:45vorm. +01:00 von Li Jia Li  notifications@github.com :

**Comment by DragonVirus** [comment]
@acorbi i don't have access to assign even to myself.

**Comment by acorbi** [comment]
True. I'll try to improve permissions a bit more later
--
Gesendet von der myMail-App für Android Dienstag, 29 November 2016, 08:18vorm. +01:00 von Li Jia Li  notifications@github.com :
