### ISSUE TITLE
Invalid Json in configuration of "Visualization Options" :JSON Parse error: Expected '}'

### ISSUE THREAD

**Issue by Huyeng** [OpenDevelopmentMekong/wp-odm_dash#79]
I tested to create the datavizs by adding the configuration following the example provided, then once viewing the page, the error of invalid json show up.

<img width="804" alt="screenshot at jun 02 15-48-01" src="https://cloud.githubusercontent.com/assets/6613530/26718240/8bfc6492-47aa-11e7-99f9-894673317898.png">

<img width="787" alt="screenshot at jun 02 15-48-28" src="https://cloud.githubusercontent.com/assets/6613530/26718239/8bb9d410-47aa-11e7-959e-ffa34e956570.png">

https://pp.opendevelopmentcambodia.net/datavizs/test/

**Comment by acorbi** [comment]
@Huyeng looks like a CORS issue:

![screenshot from 2017-06-04 11-48-33](https://cloud.githubusercontent.com/assets/384894/26760543/c5d3bd24-491b-11e7-8475-6be78a7f9fda.png)

I will coordinate this tomorrow with Proteus.

**Comment by acorbi** [comment]
@Huyeng it was indeed an issue with CORS which has been fixed by Proteus. I have updated the example details so you can copy/paste and it works, the data was updated so the previous examples were not valid anymore.

See https://pp.opendevelopmentcambodia.net/datavizs/test/
